[workspace]
resolver = "2"
members = [
    "crates/modring",
    "crates/falcon-relation",
    "crates/labrador",
    "crates/aggregate-falcon",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
proptest = "1"
rayon = "1.10"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
debug = "line-tables-only"
